import 'package:flutter/material.dart';

import '../rust/native_bridge.dart';
import '../services/script_runner.dart';
import '../theme/app_design_system.dart';
import '../widgets/profile_scope.dart';
import '../widgets/script_app_host.dart';

/// Runs a Candid-scaffolded frontend bundle (generated by
/// [FrontendScaffoldGenerator] via [FrontendScaffoldDialog]). The lightweight
/// counterpart to [DappRunnerScreen]: no DappDescriptor / asset loading / trust
/// model — just mount [ScriptAppHost] with the generated bundle and the
/// canister's connection values so the user can call methods immediately.
///
/// Authenticated effects sign as the active profile's keypair (same as the
/// shipped dapps). The strict per-method permission gate applies (no per-dapp
/// trust grant, since a scaffold is user-generated, not a shipped example).
class ScaffoldedFrontendScreen extends StatelessWidget {
  const ScaffoldedFrontendScreen({
    super.key,
    required this.title,
    required this.bundle,
    required this.canisterId,
    required this.host,
    this.testBridge,
  });

  final String title;
  final String bundle;
  final String canisterId;
  final String host;
  final ScriptBridge? testBridge;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final runtime = ScriptAppRuntime(RustScriptBridge(const RustBridgeLoader()));
    return Scaffold(
      appBar: AppBar(
        title: Tooltip(
          message: canisterId,
          child: Text(title),
        ),
        actions: [
          Padding(
            padding: const EdgeInsets.only(right: AppDesignSystem.spacing12),
            child: Chip(
              avatar: const Icon(Icons.auto_fix_high_rounded, size: 16),
              label: const Text('Scaffold'),
              backgroundColor:
                  theme.colorScheme.primaryContainer.withValues(alpha: 0.3),
              labelStyle: theme.textTheme.labelSmall,
              visualDensity: VisualDensity.compact,
            ),
          ),
        ],
      ),
      body: ScriptAppHost(
        runtime: runtime,
        script: bundle,
        initialArg: <String, dynamic>{
          'backend_id': canisterId,
          'host': host,
          'principal':
              ProfileScope.of(context, listen: false).activeKeypair?.principal ??
                  '',
        },
        authenticatedKeypair:
            ProfileScope.of(context, listen: false).activeKeypair,
        testBridge: testBridge,
      ),
    );
  }
}
