[toolchain]
channel = "stable"
profile = "default"
components = ["rustfmt", "clippy", "rust-analyzer"]
targets = [
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "x86_64-unknown-linux-gnu",
  "x86_64-linux-android",
]
