[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
ar = "llvm-ar"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"
ar = "llvm-ar"

[target.i686-linux-android]
linker = "i686-linux-android21-clang"
ar = "llvm-ar"

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
ar = "llvm-ar"

# Speed up Rust on CI by increasing codegen units, optional
[build]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
